name: Sparse checkout
description: Plugin to run sparse checkout only on selected folders
author: https://github.com/buildkite-plugins
requirements:
  - bash
configuration:
  properties:
    paths:
      type: [string, array]
    no_cone:
      type: boolean
      default: false
    skip_ssh_keyscan:
      type: boolean
      default: false
  required:
    - paths
  additionalProperties: false
