name: Sparse-checkout
description: Plugin to run sparse checkout only selected folders
author: https://github.com/buildkite-plugins
requirements:
  - bash
configuration:
  properties:
    paths:
      type: [string, array]
    no_cone:
      type: boolean
      default: false
  required:
    - paths
