steps:
  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: sparse-checkout

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files:
            - hooks/**
            - lib/**
